[options]
resize_grip = false
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
visible_bell = false
mouse_autohide = false
allow_bold = true
dynamic_title = true
urgent_on_bell = false
clickable_url = true
font = liberationmono 10
scrollback_lines = 1000
search_wrap = true
icon_name = terminal
geometry = 1002x557

# 0.0: opaque, 1.0: transparent
transparency = 0.0
pseudo_transparency = false

# "system", "on" or "off"
cursor_blink = off

# "block", "underline" or "ibeam"
cursor_shape = block

# $BROWSER is used by default
#browser = firefox

# word characters used for word selection
# (default if unset: all graphic non-punctuation/space characters)
#word_chars = -A-Za-z0-9,./?%&#:_=+@~

[colors]
foreground = #ffffff
foreground_bold = #ffffff
#foreground_dim = #ffffff
background = #1a1a1a
#cursor = #dcdccc

# if unset, will reverse foreground and background
#highlight = #

# colors from color0 to color254 can be set
# first normal, then bold

# black
color0  = #000000
color8  = #383838
# white
color7  = #A6A6A6
color15 = #FFFFFF
# red
color1  = #A62121
color9  = #FF3232
# green
color2  = #21A621
color10 = #33FF33
# yellow
color3  = #A68521
color11 = #FFCD32
# blue
color4  = #2121A6
color12 = #3232FF
# magenta
color5  = #A6217A
color13 = #FF32BB
# cyan
color6  = #217AA6
color14 = #32BBFF

[hints]
#font = Monospace 12
#foreground = #dcdccc
#background = #3f3f3f
#padding = 2
#border = #3f3f3f
#border_width = 0.5
#roundness = 2.0
